import * as Polished from "polished";

enum Base {
	PRIMARY = "#4A006F",
	SECONDARY = "#F95738",
	DANGER = "#F95738",
	ALERT = "#F95738",
	SUCCESS = "#F95738",
	BLACK = "#10161A",
	WHITE = "#FFFFFF",
}

enum Drop {
	ZERO = 0,
	ONE = 0.1,
	TWO = 0.2,
	THREE = 0.3,
	FOUR = 0.4,
	FIVE = 0.5,
	SIX = 0.6,
	SEVEN = 0.7,
	EIGHT = 0.8,
	NINE = 0.9,
}

export const Color = Object.freeze({
	PRIMARY_0: Polished.transparentize(Drop.ZERO, Base.PRIMARY),
	PRIMARY_1: Polished.transparentize(Drop.ONE, Base.PRIMARY),
	PRIMARY_2: Polished.transparentize(Drop.TWO, Base.PRIMARY),
	PRIMARY_3: Polished.transparentize(Drop.THREE, Base.PRIMARY),
	PRIMARY_4: Polished.transparentize(Drop.FOUR, Base.PRIMARY),
	PRIMARY_5: Polished.transparentize(Drop.FIVE, Base.PRIMARY),
	PRIMARY_6: Polished.transparentize(Drop.SIX, Base.PRIMARY),
	PRIMARY_7: Polished.transparentize(Drop.SEVEN, Base.PRIMARY),
	PRIMARY_8: Polished.transparentize(Drop.EIGHT, Base.PRIMARY),
	PRIMARY_9: Polished.transparentize(Drop.NINE, Base.PRIMARY),

	SECONDARY_0: Polished.transparentize(Drop.ZERO, Base.SECONDARY),
	SECONDARY_1: Polished.transparentize(Drop.ONE, Base.SECONDARY),
	SECONDARY_2: Polished.transparentize(Drop.TWO, Base.SECONDARY),
	SECONDARY_3: Polished.transparentize(Drop.THREE, Base.SECONDARY),
	SECONDARY_4: Polished.transparentize(Drop.FOUR, Base.SECONDARY),
	SECONDARY_5: Polished.transparentize(Drop.FIVE, Base.SECONDARY),
	SECONDARY_6: Polished.transparentize(Drop.SIX, Base.SECONDARY),
	SECONDARY_7: Polished.transparentize(Drop.SEVEN, Base.SECONDARY),
	SECONDARY_8: Polished.transparentize(Drop.EIGHT, Base.SECONDARY),
	SECONDARY_9: Polished.transparentize(Drop.NINE, Base.SECONDARY),

	DANGER_0: Polished.transparentize(Drop.ZERO, Base.DANGER),
	DANGER_1: Polished.transparentize(Drop.ONE, Base.DANGER),
	DANGER_2: Polished.transparentize(Drop.TWO, Base.DANGER),
	DANGER_3: Polished.transparentize(Drop.THREE, Base.DANGER),
	DANGER_4: Polished.transparentize(Drop.FOUR, Base.DANGER),
	DANGER_5: Polished.transparentize(Drop.FIVE, Base.DANGER),
	DANGER_6: Polished.transparentize(Drop.SIX, Base.DANGER),
	DANGER_7: Polished.transparentize(Drop.SEVEN, Base.DANGER),
	DANGER_8: Polished.transparentize(Drop.EIGHT, Base.DANGER),
	DANGER_9: Polished.transparentize(Drop.NINE, Base.DANGER),

	ALERT_0: Polished.transparentize(Drop.ZERO, Base.ALERT),
	ALERT_1: Polished.transparentize(Drop.ONE, Base.ALERT),
	ALERT_2: Polished.transparentize(Drop.TWO, Base.ALERT),
	ALERT_3: Polished.transparentize(Drop.THREE, Base.ALERT),
	ALERT_4: Polished.transparentize(Drop.FOUR, Base.ALERT),
	ALERT_5: Polished.transparentize(Drop.FIVE, Base.ALERT),
	ALERT_6: Polished.transparentize(Drop.SIX, Base.ALERT),
	ALERT_7: Polished.transparentize(Drop.SEVEN, Base.ALERT),
	ALERT_8: Polished.transparentize(Drop.EIGHT, Base.ALERT),
	ALERT_9: Polished.transparentize(Drop.NINE, Base.ALERT),

	SUCCESS_0: Polished.transparentize(Drop.ZERO, Base.SUCCESS),
	SUCCESS_1: Polished.transparentize(Drop.ONE, Base.SUCCESS),
	SUCCESS_2: Polished.transparentize(Drop.TWO, Base.SUCCESS),
	SUCCESS_3: Polished.transparentize(Drop.THREE, Base.SUCCESS),
	SUCCESS_4: Polished.transparentize(Drop.FOUR, Base.SUCCESS),
	SUCCESS_5: Polished.transparentize(Drop.FIVE, Base.SUCCESS),
	SUCCESS_6: Polished.transparentize(Drop.SIX, Base.SUCCESS),
	SUCCESS_7: Polished.transparentize(Drop.SEVEN, Base.SUCCESS),
	SUCCESS_8: Polished.transparentize(Drop.EIGHT, Base.SUCCESS),
	SUCCESS_9: Polished.transparentize(Drop.NINE, Base.SUCCESS),

	BLACK_0: Polished.transparentize(Drop.ZERO, Base.BLACK),
	BLACK_1: Polished.transparentize(Drop.ONE, Base.BLACK),
	BLACK_2: Polished.transparentize(Drop.TWO, Base.BLACK),
	BLACK_3: Polished.transparentize(Drop.THREE, Base.BLACK),
	BLACK_4: Polished.transparentize(Drop.FOUR, Base.BLACK),
	BLACK_5: Polished.transparentize(Drop.FIVE, Base.BLACK),
	BLACK_6: Polished.transparentize(Drop.SIX, Base.BLACK),
	BLACK_7: Polished.transparentize(Drop.SEVEN, Base.BLACK),
	BLACK_8: Polished.transparentize(Drop.EIGHT, Base.BLACK),
	BLACK_9: Polished.transparentize(Drop.NINE, Base.BLACK),

	WHITE_0: Polished.transparentize(Drop.ZERO, Base.WHITE),
	WHITE_1: Polished.transparentize(Drop.ONE, Base.WHITE),
	WHITE_2: Polished.transparentize(Drop.TWO, Base.WHITE),
	WHITE_3: Polished.transparentize(Drop.THREE, Base.WHITE),
	WHITE_4: Polished.transparentize(Drop.FOUR, Base.WHITE),
	WHITE_5: Polished.transparentize(Drop.FIVE, Base.WHITE),
	WHITE_6: Polished.transparentize(Drop.SIX, Base.WHITE),
	WHITE_7: Polished.transparentize(Drop.SEVEN, Base.WHITE),
	WHITE_8: Polished.transparentize(Drop.EIGHT, Base.WHITE),
	WHITE_9: Polished.transparentize(Drop.NINE, Base.WHITE),

	TRANSPARENT: Polished.transparentize(1, Base.BLACK),
});

export type Color = typeof Color[keyof typeof Color];
