name: CI
on:
  push:
    branches: [master, develop, alpha]
  pull_request:
    branches: [master, develop, alpha]

jobs:
  release-libraries:
    name: Release Libraries
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        id: release-libraries-1
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        id: release-libraries-2
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "10.19.0"
          registry-url: https://registry.npmjs.org/
          scope: lunaris-studios

      - name: Set Git Indentity
        id: release-libraries-3
        run: |
            git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
            git config --global user.name ${{ secrets.GIT_USER_NAME }}

      - name: Install Node.js dependencies
        id: release-libraries-4
        run: |
          npm ci

      # - name: Test Libraries
      #   id: release-libraries-5
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #   run: |
      #     npm run test

      - name: Bootstrap Local Dependencies
        id: release-libraries-6
        run: |
          npm run bootstrap

      - name: Build Production Libraries
        id: release-libraries-7
        run: |
          npm run dist:libs

      - name: Publish Libraries
        id: release-libraries-8
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm run release
