name: CI
on:
  push:
    branches: [master, develop, alpha]
  pull_request:
    branches: [master, develop, alpha]

jobs:
  release-libraries:
    name: Release Libraries
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        id: build-1
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        id: build-2
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "10.19.0"
          registry-url: https://registry.npmjs.org/
          scope: lunaris-studios

      - name: Set Git Indentity
        id: build-3
        run: |
            git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
            git config --global user.name ${{ secrets.GIT_USER_NAME }}

      - name: Install Node.js dependencies
        id: build-4
        run: |
          npm ci

      # - name: Run Tests
      #   id: build-5
      #   run: |
      #     npm run test

      - name: Release
        id: build-5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm run release:libs
